packages:
  - apps/*
  - packages/*

catalog:
  '@typescript-eslint/eslint-plugin': ^8.51.0
  '@typescript-eslint/parser': ^8.51.0
  eslint: 9.39.2
  eslint-config-prettier: ^10.1.8
  prettier: ^3.7.4
  prettier-plugin-tailwindcss: ^0.7.2
  tailwindcss: ^4.1.18
  turbo: ^2.7.2
  typescript: ^5.9.3
  unbuild: ^3.6.1
  vite: ^7.3.0
